version: "3.9"

services:
  db:
    image: postgres
    container_name: ${PREFIX:?}_db-${ENV:?}
    restart: unless-stopped
    volumes:
      - /var/lib/postgresql/data
    env_file: .env.prod
    environment:
      POSTGRES_DB: ${DB_NAME:?}
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}

  api:
    image: social-lead-generator_api:latest
    container_name: ${PREFIX:?}_api-${ENV:?}
    command: uvicorn --host 0.0.0.0 app:app --reload
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file: .env.prod

  webapp:
    image: social-lead-generator_webapp:latest
    container_name: ${PREFIX:?}_webapp-${ENV:?}
    restart: on-failure
    depends_on:
      - api
    volumes:
      - /data
      - /config
    ports:
      - 80:80
