version: "3.8"

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    env_file: ./postgres/.env

  api:
    image: social-lead-generator_api:latest
    command: uvicorn --host 0.0.0.0 app:app --reload
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file: ./api/.env.prod

  webapp:
    image: social-lead-generator_webapp:latest
    restart: on-failure
    depends_on:
      - api
    volumes:
      - ./webapp/caddy/data:/data
      - ./webapp/caddy/config:/config
    ports:
      - 80:80
