version: "3.8"

services:
  api:
    build: ./api
    command: uvicorn --host 0.0.0.0 app:app --reload
    restart: on-failure
    volumes:
      - ./api:/srv/api
    ports:
      - 8000:8000
    env_file: ./api/.env

  webapp:
    build: ./webapp
    restart: on-failure
    depends_on:
      - api
    volumes:
      - ./webapp/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./webapp/caddy/data:/data
      - ./webapp/caddy/config:/config
    ports:
      - 3000:80
