version: "3.9"

services:
  db:
    image: postgres
    container_name: ${PREFIX:?}_db-${ENV:?}
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file: .env.prod
    environment:
      POSTGRES_DB: ${DB_NAME:?}
      POSTGRES_USER: ${DB_USER:?}
      POSTGRES_PASSWORD: ${DB_PASSWORD:?}

  api:
    image: sadmanahmed/social-lead-generator_api:latest
    container_name: ${PREFIX:?}_api-${ENV:?}
    command: sh -c 'while ! nc -z ${DB_HOST:?} ${DB_PORT:?}; do sleep 1; done; uvicorn --host 0.0.0.0 app:app --reload'
    restart: on-failure
    depends_on:
      - db
    ports:
      - 8000:8000
    env_file: .env.prod

  webapp:
    image: sadmanahmed/social-lead-generator_webapp:latest
    container_name: ${PREFIX:?}_webapp-${ENV:?}
    restart: on-failure
    depends_on:
      - api
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    ports:
      - 80:80

volumes:
  db-data-${ENV}:
  caddy-data:
  caddy-config:
