version: "3.8"

services:
  # db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_DB=postgres
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  backend:
    build: .
    command: uvicorn --host 0.0.0.0 app:app --reload
    volumes:
      - .:/srv/backend
    ports:
      - 8000:8000
    # depends_on:
    #   - db
    env_file: .env